### ISSUE TITLE
create releases with github actions from jla_01, rlp_01 repositories [$150]

### ISSUE THREAD

**Issue by kortemik** [teragrep/teragrep#1]
configure github actions for jla_01 and rlp_01 repositories to produce artifacts for maven central.
configure coverity to scan vulnerabilities.

**Comment by kortemik** [comment]
coverity is missing for rlp_01

**Comment by RedTurtleDonkey** [comment]
On push:
  Test
  Verify

On release:
  Deploy to OSSRH using release tag

Have any changes that you want?

**Comment by kortemik** [comment]
I think the automatic upload to coverity is something that we would still need.

**Comment by kortemik** [comment]
is there something in progress still?

**Comment by RedTurtleDonkey** [comment]
On push:
  Verify
  Send to Coverity
On release:
  Deploy to OSSRH (disabled)

To do:
  .github/workflows/ci.yaml
    setup repository secret for your coverity token
      found on the automation section when you are attemping to submit a build for any project
  .github/workflows/upload_release.yaml
    setup repository or organisation secrets for
      ossrh username
      ossrh token
      gpg private key
      gpg passphrase
  pom.xml
    add a public email for the developer section

Broken:
  Coverity
    components for jla_01 results in page not found 404
    upload with ci.yaml also results in a page not found 404 error

As of now, every push is verified and compiled with coverity's analysis tool but the result is not uploaded to Coverity Scan.
Releasing hasn't been tested.

**Comment by kortemik** [comment]
please change the commiter email from user to yours so CLA assistant marks the submissions ok and let's close this issue and you'll get the bounty!

**Comment by RedTurtleDonkey** [comment]
Fixed, please keep me updated on Coverity, it's still bugged for me

**Comment by kortemik** [comment]
```
       <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url> 
```
should be 
```
       <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url> 
```
i think because we do have only credentials on the older system

developer email is 1@teragrep.com

tokens have been set up

please change maven to use -B and curl -q so that the download output does not flood the output logs

**Comment by kortemik** [comment]
releasing fails
https://github.com/teragrep/rlp_01/actions/runs/654017880

**Comment by RedTurtleDonkey** [comment]
Releasing should work now, I'll see if I can get rid of the repeating old commits before pulling on jla.

**Comment by kortemik** [comment]
From publish stage of https://github.com/teragrep/rlp_01/runs/2112978952?check_suite_focus=true
```
[INFO] Skipping artifact deployment
```
I think on the pom.xml this needs to be altered https://github.com/teragrep/rlp_01/blob/master/pom.xml#L103

We use internally following so that's why maven-deploy-plugin was configured as skipped.
```
<plugin>
  <groupId>org.sonatype.plugins</groupId>
  <artifactId>nexus-staging-maven-plugin</artifactId>
  <version>1.6.7</version>
  <executions>
    <execution>
      <id>nexus-deploy</id>
      <phase>deploy</phase>
      <goals>
        <goal>deploy</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <serverId>ZZ</serverId>
    <nexusUrl>https://YY.DOMAIN.TLD</nexusUrl>
    <skipStaging>true</skipStaging>
    <stagingRepositoryId>XXX</stagingRepositoryId>
  </configuration>
</plugin>
```

It seems that they recommend using the similar approach in https://central.sonatype.org/pages/apache-maven.html

**Comment by RedTurtleDonkey** [comment]
Transfer failed for https://oss.sonatype.org/service/local/staging/deploy/maven2/com/teragrep/rlp_01/3.0.0/rlp_01-3.0.0.jar 401 Unauthorized

So it seems to be trying.

I've prepared the nexus staging plugin in case maven deployment doesn't work.

**Comment by kortemik** [comment]
same error https://github.com/teragrep/rlp_01/runs/2114123005?check_suite_focus=true

**Comment by RedTurtleDonkey** [comment]
Gpg signing is not as automatic as I though so it is added now.
Unfortunately signing is one of ossrh's requirements so testing deploy with the nexus staging plugin will be delayed.
Right now the gpg plugin is refusing to use the passphrase in settings.xml

**Comment by kortemik** [comment]
https://github.com/teragrep/rlp_01/runs/2191590465?check_suite_focus=true it seems to fail with the upload still although the signing works now:

https://github.com/teragrep/rlp_01/runs/2191590420?check_suite_focus=true
```
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ rlp_01 ---
```

**Comment by RedTurtleDonkey** [comment]
Not sure why it's looking for settings-security.xml, it isn't mentioned in any of the documentations and gpg-passphrase isn't encrypted using a master password.

"GPG credentials being available e.g. from settings.xml." The passphrase exists in the generated settings.xml file so it should be using that.

settings-security.xml could be manually created but it shouldn't be necessary according to the documents and other projects so I'll keep looking.

Sorry about the delays, the internet around here has been down for hours at a time, it's gotten better so I should be able to work now.

**Comment by kortemik** [comment]
no worries, sorry about the delays on my part as well. we are quite busy preparing the next open source releases so you can expect more bounties to come on the repository.

**Comment by kortemik** [comment]
i think the security-settings.xml is not about the GPG but rather than the OSSRH credentials maven uses to authenticate to sonatypes repository which we have saved as following secrets:
```
 MAVEN_CENTRAL_TOKEN 
```
and
```
 MAVEN_CENTRAL_USERNAME 
```

**Comment by kortemik** [comment]
following might be useful https://stackoverflow.com/a/55970125/14512212

**Comment by RedTurtleDonkey** [comment]
Thanks, you were correct, setup-java wants the maven token and gpg passphrase as env variables for whatever reason.

**Comment by kortemik** [comment]
https://github.com/teragrep/rlp_01/runs/2191590465?check_suite_focus=true still the same

**Comment by kortemik** [comment]
https://docs.github.com/en/actions/guides/publishing-java-packages-with-maven

**Comment by RedTurtleDonkey** [comment]
Sorry about the delay.

I'm still waiting on my ossrh namespace so I can test the workflows and pom.xml myself.

I have three possibilities so far:
- Manually encrypt with the terminal
- Only use the nexus staging plugin, which follows ossrh recommendations
- Only use the maven deploy plugin, which is recommended by the setup-java action

Unless you want to take advantage of staging, the nexus plugin probably isn't needed.
Using the maven deploy plugin is probably the most reliable option.

I still don't know the exact cause of this issue, I'll be able to find it quicker once my namespace is reserved.

**Comment by kortemik** [comment]
please use the one on the github actions guide, it should work. I think it's using the maven deploy plugin, most likely.

**Comment by kortemik** [comment]
https://github.com/teragrep/rlp_01/runs/2435626943?check_suite_focus=true

it works, i had to change java version from 1.8 to 8.xx one though. it's now staged, not published

**Comment by kortemik** [comment]
https://www.youtube.com/watch?v=dXR4pJ_zS-0 seems like ossrh likes the staging

**Comment by kortemik** [comment]
Seems like we hit https://issues.sonatype.org/browse/OSSRH-31614 where they have requirements of:
```
If you're not already doing so, have a look at our official guide for Apache Maven:

http://central.sonatype.org/pages/apache-maven.html

specifically, these sub-sections related to sources, javadocs, and signatures:

http://central.sonatype.org/pages/apache-maven.html#javadoc-and-sources-attachments
http://central.sonatype.org/pages/apache-maven.html#gpg-signed-components
```

**Comment by RedTurtleDonkey** [comment]
At 5:04 on the video, what errors come up?

Is this only for jla?

https://github.com/RedTurtleDonkey/jla_01/runs/2508281127?check_suite_focus=true#step:5:139
jla is fetching rlp from maven central to build so it seems like rlp is successfully published.

The pom for jla is missing an email for the developer section.

**Comment by kortemik** [comment]
I was able to get the publishing working so there is left coverity, adding github releases would be ok if that's not too much.

Changes basically required were:
https://github.com/teragrep/jla_01/commit/ef0aca609087808da5c8ca094f1c4309a3e91b70

**Comment by kortemik** [comment]
github packages, but that's optional. coverity is required.

**Comment by RedTurtleDonkey** [comment]
Should the projects be formatted to the maven standard? https://maven.apache.org/developers/conventions/code.html

Maven recommends two space indents for xmls.
They also have an order for pom elements.

**Comment by kortemik** [comment]
coverity works. github packages should be built as:
        run: mvn --batch-mode -Drevision=${{ github.event.release.tag_name }} -Dsha1= -Dchangelist= clean deploy -Ppublish-github-packages

otherwise tag based releasing does not work and the packages are produced with 0.0.1-SNAPSHOT as their version.

**Comment by kortemik** [comment]
i commited the github packaging changes. I think this is all for now. Thank you @RedTurtleDonkey the bounty is yours.
